Gopkg.lock, input/fileprovider.go, input/fileprovider_test.go
Move path input from init to `LocalPath` function parameter. This way `FileProvider` is reusable and could be used to handle multiple files.
=> [NOJIRA] Move path from FileProvider init to function param

stepconf/stepconf.go
Break `stepconf.Parse`  dependency on `os.Getenv`, to facilitate unit testing.
Use-case: https://github.com/bitrise-steplib/steps-xcode-archive/pull/227/files#diff-79ce3229c13921b79b1175dcb211336aaf84dfd8edcf19c07698934d4fe70e5eR109-R112
=> Break stepconf.Parse os.Getenv dependency.

go.mod, go.sum, output/output.go, output/output_test.go
The zip function gained multi file support in the go-utils repo and this PR bring the same multi file support.
The `func ZipAndExportOutput(sourcePths []string, destinationZipPth, envKey string) error` can now export one of the following options:
- Single file
- Multiple files
- Single folder
This multi file export is being introduced because the way we find the dSYM files has changed. An application can have multiple app level dSYM (like main app, appclip, watch app, different extensions, ...) so it is no longer enough to export only one dSYM.
=> Multi file export update

stepconf/strings.go, stepconf/strings_test.go
`stepconf.Print()` is used by every step to print the step input keys and values to the build log. However, the printed key is the name of the struct field instead of the key defined in `step.yml`. This is confusing not just because of the casing (`LogFormatter` vs `log_formatter`) but because sometimes the field has a slightly different name (`ExportMethod` vs `distribution_method`)
- Look up the step.yml key (defined as struct tags) if possible, and use the field name otherwise
- When the field value is empty, print `key: <empty value>`
- Add tests
```
Inputs:
- ExportMethod: development
- UploadBitcode: true
- CompileBitcode: true
- ICloudContainerEnvironment:
- ExportDevelopmentTeam:
- ExportOptionsPlistContent:
- LogFormatter: xcodebuild
- ProjectPath: …
```
=> Better input printing

stepconf/strings.go, stepconf/strings_test.go
`reflect.Value.IsZero()` returns true for `false` and `0` values, so those input values are printed as `<unset>` at the moment.
There is no way to differentiate undefined boolean and numeric inputs from `false` and `0`, but it's still better to print undefined inputs as `false` and `0` than printing explicit `false` and `0` input values as `<unset>`
=> Fix printing false and 0 input values

cache/keytemplate/keytemplate.go, cache/keytemplate/keytemplate_test.go
Introduce a new package to handle cache key template parsing. This will be a shared dependency of the `save-cache` and `restore-cache` steps.
See the test cases for a few practical examples.
Matching PR in a step: https://github.com/bitrise-steplib/bitrise-step-save-cache/pull/4
- Implement template parsing on top of the `text/template` package
- Expose a few template variables and functions
Implementing the `checksum` template function is out of scope for this PR, that will come later.
=> Cache key template parsing

cache/keytemplate/checksum.go, cache/keytemplate/checksum_test.go, cache/keytemplate/keytemplate.go, cache/keytemplate/keytemplate_test.go, cache/keytemplate/testdata/app/build.gradle, cache/keytemplate/testdata/build.gradle, cache/keytemplate/testdata/build.gradle.kts, cache/keytemplate/testdata/package-lock.json, go.mod, go.sum
This PR improves the cache key template handling added in #50, by implementing the `checksum` template function.
- Compute SHA-256 checksums of one or more files
- Multiple files are handled by feeding the raw bytes into the hash algo sequentially (after sorting the file paths)
- Add support for glob patterns, including "doublestar" (`**/*.gradle`), using https://github.com/bmatcuk/doublestar
See tests for actual pattern examples.
=> Add `checksum` template function

ruby/command.go, ruby/command_test.go, ruby/environment.go, ruby/environment_test.go, ruby/mocks/CommandLocator.go
This update adds support for Ruby versions installed using the [asdf version manager](https://asdf-vm.com). asdf is not currently used in CI, but it is a popular tool for developers to use on their machines — and selfishly, it's what I use on my machine. :)
This change builds off of work by @matrangam in https://github.com/bitrise-io/go-steputils/pull/46, but goes a couple steps further by adding asdf reshimming when gems are installed, and a more accurate check for if ruby is installed via asdf.
- Adds `ASDFRuby` type ([here](https://github.com/bitrise-io/go-steputils/pull/53/files#diff-2e55ae2cb609a670cb5e604220dc4cc807e12280874deb8146570bf4b30fef19R36-R37)) and a check for it in `rubyInstallType` ([here](https://github.com/bitrise-io/go-steputils/pull/53/files#diff-2e55ae2cb609a670cb5e6 …
=> Add support for asdf-managed Ruby installs

cache/keytemplate/checksum.go
The cache key checksum function tries to hash every parameter passed to it, even if it’s not a file. Right now it results in the following warning:
```
Error while hashing .gradle: read .gradle: is a directory
```
This happens when the cache key uses glob patterns that are meant to match files but also match a similarly named folder: `gradle-cache-{{ checksum "**/*.gradle" "/gradle-wrapper.properties" }}`
After evaluating the glob patterns, filter out the directories from the matched paths.
Note: there is already a test case that covers this scenario, so I only added the appropriate test folder structure to trigger the scenario.
=> Skip directories in hashing

cache/keytemplate/keytemplate.go
This warning is not really actionable for the user, so it feels strange to see this warning in the logs.
Also, the `.CommitHash` variable is one that is often not defined, for example in manually triggered builds.
=> Log cache template warning as debug

cache/keytemplate/checksum.go, cache/keytemplate/checksum_test.go
Pattern matching in the `checksum` template function is not working when the path is an absolute path (or one that gets expanded to an absolute path), such as:
```
~/Library/Developer/Xcode/DerivedData/**/SourcePackages
```
Fix glob pattern matching by splitting the path input into a base path and a pattern. Relevant section from the docs of `doublestar.Glob()`:
> // Like `io/fs.Glob()`, patterns containing `/./`, `/../`, or starting with `/`
> // will return no results and no errors. You can use SplitPattern to divide a
> // pattern into a base path (to initialize an `FS` object) and pattern.
=> Fix pattern matching in absolute paths

.golangci.yml, bitrise.yml, go.mod, go.sum, output/output_test.go, ruby/command.go, ruby/environment.go, stepconf/strings.go
Use the standard linters and config we use in other step repos.
This PR drops `errcheck` and `golint` in favor of `golangci-lint` through the `check` internal step.
There were a few lint violations with the new rules, this PR fixes those.
```
output/output_test.go:112:6: `givenTmpLogFilePath` is unused (deadcode)
func givenTmpLogFilePath(t *testing.T) string {
^
output/output_test.go:119:6: `requireFileContents` is unused (deadcode)
func requireFileContents(t *testing.T, contents, filePath string) {
^
stepconf/strings.go:20:11: S1039: unnecessary use of fmt.Sprintf (gosimple)
return fmt.Sprintf("<unset>")
^
ruby/environment.go:149:13: S1007: should use raw string (`...`) with regexp.Compile to avoid having to escape twice (gosimple)
reg, err = regexp.Compile(".* \\(set by")
^ …
```
=> Use standard linters

cache/network/upload.go, cache/network/upload_test.go, cache/save.go, cache/save_test.go
- Add a warning when the cache key is too long and gets truncated
- Fix using the evaluated cache key instead of the raw template
=> Small fixes

cache/keytemplate/keytemplate.go, cache/keytemplate/keytemplate_test.go, cache/restore.go, cache/save.go
The `.CommitHash` template variable is bound to the `BITRISE_GIT_COMMIT` env var, which is bound to the build trigger's commit hash value. This input is optional, usually manually triggered builds don't specify a commit hash.
In these cases, we can use a fallback value: the git clone step's output value for the actual commit hash (after checking out the specified branch).
- Use the second env var's value as fallback and print a log statement
- Remove `BuildContext` struct and move env var parsing from the consumers to the `Evaluate()` method
=> Use fallback commit hash value

cache/common.go, cache/keytemplate/checksum.go, cache/network/api.go, cache/network/download.go, cache/restore.go, cache/restore_test.go, cache/save.go, cache/save_skip.go, cache/save_skip_test.go, cache/save_test.go, cache/tracker.go, integration/download_test.go
The full context and idea is described in [ACI-4](https://bitrise.atlassian.net/jira/software/c/projects/ACI/boards/280?modal=detail&selectedIssue=ACI-4)
- The restore API endpoint now returns the exact matched key, surface this information in return values
- `Restorer` now exposes the matched key as an env var if there is a cache hit
- `Saver` checks these cache hit env vars and can decide to skip
- both compression and upload
- just upload if it needs to compute a checksum of the new archive to make sure it's the same as before
- log an event in `Restorer` with details about the key match
Event logging in `Saver`. I want to beta test this whole logic in the wild to see what we want to log exactly and to figure out the best schema.
=> Skip saving the cache if possible

.golangci.yml, cache/restore.go, cache/restore_test.go, cache/save.go, cache/save_skip.go, cache/save_skip_test.go, cache/tracker.go, stepconf/stepconf.go
Follow-up to #67, this PR adds tracking when we can skip saving the cache altogether and when we can only skip the upload.
- Log new events with the skip result and reason
- Refactor the skip reason handling with enums
- Enable the `exhaustive` linter in order to check `switch` expressions on enums
- Adjust tests
- Smaller adjustments here and there
=> Track cache skip reasons

bitrise.yml, cache/restore.go, cache/restore_test.go, cache/save.go, cache/save_test.go, integration/download_test.go, integration/upload_test.go
Update the cache API token handling throughout the code with the new env key (this is injected into the VM automatically).
=> Update cache API token handling

cache/common.go, cache/restore.go, cache/restore_test.go, cache/save_skip.go
Exposing cache hit information as a public step output in order to build conditional workflows based on the cache restore result.
- Expose `BITRISE_CACHE_HIT` output with 3 possible values: `exact`, `partial`, `false`
=> Expose cache hit info as output

go.mod, go.sum, stepconf/strings.go
When using this dependency in vendored projects, I noticed a sudden growth in the vendor folder size (after an upgrade from a previous `go-steputils` version).
Seems like in #61 I added the `golang.org/x/text` dependency to replace a deprecated usage of `strings.Title()`. It got deprecated in Go 1.18 because it doesn't handle complex Unicode data, but our use case only involves title-casing a Go struct's name, so I think we'll be fine with `strings.Title()`.
By getting rid of the `/x/text` dependency, a step relying on `go-steputils` will have -65K LoC in the vendor folder:
```
❯ git diff --stat
go.mod                                                           |    3 +-
go.sum                                                           |    4 - …
```
=> Remove /x/text dependency

bitrise.yml, cache/network/api.go, cache/network/mocklogger_test.go, cache/network/upload.go, cache/network/upload_test.go, integration/upload_test.go
Cache API now returns an additional debug/warning message about cache quota. This change makes the cache upload print this message with the appropriate log color.
- Update API response handling
- Print message in the API response according to the given severity
- Tests
=> Print API response after cache upload

cache/restore_test.go, export/export_test.go
Getting rid of the last few remaining v1 `go-utils` usages.
- Replace usages of `go-utils/pathutil.RevokableChangeDir()` with `t.Cleanup()` and a few lines of custom code
- Replace usages of `go-utils/envutil.RevokableSetEnv()` with `t.Setenv()` (which reverts the env after the test)
=> Remove v1 go-utils usage in tests

cache/network/api.go, cache/network/download.go, cache/network/upload.go, cache/save_test.go
We noticed that the `Content-Length` header is missing from the upload request. This is probably a bug in the `retryablehttp` client, so this PR sets the content length manually.
=> Fix Content-Length header in cache upload request

ruby/environment.go
Ruby installation type is detected as asdf if asdf both is in path and in the Ruby shims path.
=> Fix asdf Ruby lokup

cache/network/download.go, cache/network/download_test.go, cache/restore.go
Currently the download URL is valid for 1 minute. This prevents the "full retry" to work after that time.
Updated "full retry" to include fetching of the signed download URL.
The signed URL lifetime is not changed at the moment.
=> Retry download url

cache/compression/compression.go
Print the default errors returned by v2 command: https://github.com/bitrise-io/go-utils/blob/9606561f924c4ea4ddc71189256a20f4499cd396/command/command.go#L168.
This solves the issue that the ExitError is not returned currently by command package (to be solved in an other PR), and reusing the default "known good" error handling.
=> Fix compress command outputs

cache/keytemplate/checksum.go, cache/save.go, go.mod, go.sum, vendor/github.com/bmatcuk/doublestar/v4/.codecov.yml, vendor/github.com/bmatcuk/doublestar/v4/README.md, vendor/github.com/bmatcuk/doublestar/v4/doublestar.go, vendor/github.com/bmatcuk/doublestar/v4/glob.go, vendor/github.com/bmatcuk/doublestar/v4/globoptions.go, vendor/github.com/bmatcuk/doublestar/v4/globwalk.go, vendor/github.com/bmatcuk/doublestar/v4/match.go, vendor/github.com/bmatcuk/doublestar/v4/utils.go, vendor/github.com/gofrs/uuid/v5/.pre-commit-config.yaml, vendor/modules.txt
Updated `doublestar` so we could add the flags at all.
=> Ignore symlinks during path evaluation
